-- review_flags: auto-raised flags on individual calls, generated by the
-- rule-based flagging engine (spec section 2.2 / section 4).

create table review_flags (
  flag_id uuid primary key default gen_random_uuid(),
  call_id uuid not null references calls (call_id) on delete cascade,
  flag_type flag_type not null,
  raised_at timestamptz not null default now(),
  reason text,
  reviewed_by text,
  reviewed_at timestamptz,
  reviewer_notes text,
  resolved boolean not null default false
);

create index review_flags_call_id_idx on review_flags (call_id);
create index review_flags_unresolved_idx on review_flags (resolved) where resolved = false;
create index review_flags_flag_type_idx on review_flags (flag_type);
